export const SUPPORTED_FILE_ACCEPT_VALUES = [
  'audio/*',
  'video/*',
  '.mp3',
  '.wav',
  '.m4a',
  '.flac',
  '.ogg',
  '.aac',
  '.wma',
  '.mpeg',
  '.mpga',
  '.mp4',
  '.mov',
  '.avi',
  '.mkv',
  '.webm',
  '.wmv',
  '.flv',
  '.m4v',
  '.pdf',
  '.docx',
  '.pptx',
  '.xlsx',
  '.txt',
  '.png',
  '.jpg',
  '.jpeg',
  '.tiff',
  '.tif',
  'application/pdf',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'text/plain',
  'image/png',
  'image/jpeg',
  'image/tiff'
] as const

export const SUPPORTED_FILE_ACCEPT = SUPPORTED_FILE_ACCEPT_VALUES.join(',')
