import * as v from 'valibot'
import { DocumentRuntimeCapabilitiesSchema } from './step-2-document-types'
import { LLMServiceTypeSchema } from './step-3-types'
import { ImageGenServiceTypeSchema,MusicBitrateSchema,MusicPresetSchema,MusicSampleRateSchema,MusicServiceTypeSchema,VideoGenServiceTypeSchema } from './step-4-types'

export const StepsStateSchema = v.object({
  transcriptionOption: v.string(),
  transcriptionModel: v.pipe(v.string(), v.nonEmpty()),
  transcriptionModelSelected: v.boolean(),
  selectedPrompts: v.array(v.string()),
  llmEnabled: v.boolean(),
  ttsWithLlm: v.boolean(),
  writeModeSelected: v.boolean(),
  llmService: LLMServiceTypeSchema,
  llmModel: v.pipe(v.string(), v.nonEmpty()),
  llmModelSelected: v.boolean(),
  llmCustomInstructions: v.string(),
  ttsService: v.string(),
  ttsVoice: v.string(),
  ttsModel: v.pipe(v.string(), v.nonEmpty()),
  ttsModelSelected: v.boolean(),
  ttsVoiceSelected: v.boolean(),
  ttsDecisionMade: v.boolean(),
  imageEnabled: v.boolean(),
  mediaDecisionSelected: v.boolean(),
  imageService: ImageGenServiceTypeSchema,
  imageModel: v.pipe(v.string(), v.nonEmpty()),
  imageModelSelected: v.boolean(),
  imageDimensionOrRatio: v.pipe(v.string(), v.nonEmpty()),
  imageDimensionSelected: v.boolean(),
  selectedImagePrompts: v.array(v.string()),
  imagePromptSelected: v.boolean(),
  imageCustomInstructions: v.string(),
  musicEnabled: v.boolean(),
  musicService: MusicServiceTypeSchema,
  musicModel: v.pipe(v.string(), v.nonEmpty()),
  musicModelSelected: v.boolean(),
  selectedMusicGenre: v.string(),
  musicGenreSelected: v.boolean(),
  musicPreset: MusicPresetSchema,
  musicPresetSelected: v.boolean(),
  musicDurationSeconds: v.pipe(v.number(), v.integer(), v.minValue(3), v.maxValue(300)),
  musicDurationSelected: v.boolean(),
  musicInstrumental: v.boolean(),
  musicSampleRate: v.optional(MusicSampleRateSchema, undefined),
  musicBitrate: v.optional(MusicBitrateSchema, undefined),
  musicCustomInstructions: v.string(),
  videoEnabled: v.boolean(),
  videoService: VideoGenServiceTypeSchema,
  selectedVideoPrompts: v.array(v.string()),
  videoPromptSelected: v.boolean(),
  videoModel: v.pipe(v.string(), v.nonEmpty()),
  videoModelSelected: v.boolean(),
  videoSize: v.string(),
  videoSizeSelected: v.boolean(),
  videoDuration: v.number(),
  videoDurationSelected: v.boolean(),
  videoAspectRatio: v.string(),
  videoAspectRatioSelected: v.boolean(),
  videoCustomInstructions: v.string(),
  selectedFile: v.nullable(v.any()),
  uploadId: v.string(),
  uploadedFileName: v.string(),
  uploadedFileSize: v.optional(v.pipe(v.number(), v.integer(), v.minValue(0)), undefined),
  uploadedFileDuration: v.optional(v.number(), undefined),
  sourceOrigin: v.nullable(v.union([v.literal('local-upload'), v.literal('google-drive')])),
  isUploading: v.boolean(),
  uploadError: v.string(),
  uploadProgress: v.number(),
  urlValue: v.string(),
  isVerifying: v.boolean(),
  urlMetadata: v.any(),
  urlVerified: v.boolean(),
  documentRuntimeCapabilities: v.nullable(DocumentRuntimeCapabilitiesSchema),
  documentService: v.string(),
  documentModel: v.string(),
  documentModelSelected: v.boolean()
})
