import * as v from 'valibot'
import { DocumentExtractionServiceTypeSchema,SupportedDocumentTypeSchema } from './step-2-document-types'
import { InputTypeSchema } from './step-1-types'
import { TranscriptionServiceTypeSchema } from './step-2-transcription-types'
import { ImageGenServiceTypeSchema,MusicBitrateSchema,MusicPresetSchema,MusicSampleRateSchema,MusicServiceTypeSchema } from './step-4-types'
import { BigIntSchema,NullableBigIntSchema,NullableSqliteBooleanSchema } from './validation-types'

export const ShowNoteIdSchema = v.pipe(
  v.string(),
  v.nonEmpty(),
  v.regex(/^[a-zA-Z0-9_-]+$/, 'Show note ID must contain only alphanumeric characters, hyphens, and underscores')
)

export const ShowNoteAssetKindSchema = v.picklist(['llm', 'tts', 'image', 'music', 'video'])

export const ShowNoteAssetSchema = v.object({
  id: v.pipe(v.string(), v.nonEmpty()),
  show_note_id: ShowNoteIdSchema,
  job_id: v.pipe(v.string(), v.nonEmpty()),
  kind: ShowNoteAssetKindSchema,
  service: v.nullable(v.string()),
  model: v.nullable(v.string()),
  file_path: v.nullable(v.string()),
  thumbnail_file_path: v.nullable(v.string()),
  metadata_json: v.nullable(v.string()),
  created_at: BigIntSchema,
  updated_at: BigIntSchema
})

export const ShowNoteSchema = v.object({
  id: v.pipe(v.string(), v.nonEmpty()),
  total_cost_usd: v.optional(v.nullable(v.number())),
  url: v.pipe(v.string(), v.nonEmpty()),
  title: v.pipe(v.string(), v.nonEmpty()),
  author: v.nullable(v.string()),
  duration: v.nullable(v.string()),
  prompt: v.nullable(v.string()),
  text_output: v.nullable(v.string()),
  transcription: v.string(),
  transcription_service: v.nullable(TranscriptionServiceTypeSchema),
  transcription_model: v.nullable(v.string()),
  document_service: v.nullable(DocumentExtractionServiceTypeSchema),
  document_model: v.nullable(v.string()),
  document_type: v.nullable(SupportedDocumentTypeSchema),
  document_page_count: NullableBigIntSchema,
  document_processing_time: NullableBigIntSchema,
  document_character_count: NullableBigIntSchema,
  document_input_token_count: NullableBigIntSchema,
  document_output_token_count: NullableBigIntSchema,
  document_cost: v.nullable(v.pipe(v.number(), v.minValue(0))),
  llm_service: v.nullable(v.union([v.literal('openai'), v.literal('claude'), v.literal('gemini'), v.literal('minimax'), v.literal('deepinfra'), v.literal('grok'), v.literal('groq'), v.literal('glm')])),
  llm_model: v.nullable(v.string()),
  processed_at: BigIntSchema,
  created_at: BigIntSchema,
  estimated_processing_breakdown: v.nullable(v.string()),
  video_publish_date: v.nullable(v.string()),
  video_thumbnail: v.nullable(v.string()),
  channel_url: v.nullable(v.string()),
  audio_file_name: v.nullable(v.string()),
  audio_file_size: NullableBigIntSchema,
  transcription_processing_time: NullableBigIntSchema,
  transcription_token_count: NullableBigIntSchema,
  transcription_cost: v.nullable(v.pipe(v.number(), v.minValue(0))),
  llm_processing_time: NullableBigIntSchema,
  llm_input_token_count: NullableBigIntSchema,
  llm_output_token_count: NullableBigIntSchema,
  llm_cost: v.nullable(v.pipe(v.number(), v.minValue(0))),
  selected_prompts: v.nullable(v.string()),
  tts_enabled: NullableSqliteBooleanSchema,
  tts_service: v.nullable(v.union([v.literal('openai'), v.literal('elevenlabs'), v.literal('deepgram'), v.literal('gemini'), v.literal('grok'), v.literal('groq'), v.literal('runway'), v.literal('deapi')])),
  tts_model: v.nullable(v.string()),
  tts_voice: v.nullable(v.string()),
  tts_audio_file: v.nullable(v.string()),
  tts_processing_time: NullableBigIntSchema,
  tts_audio_duration: v.nullable(v.pipe(v.number(), v.minValue(0))),
  tts_cost: v.nullable(v.pipe(v.number(), v.minValue(0))),
  image_gen_enabled: NullableSqliteBooleanSchema,
  image_gen_service: v.nullable(ImageGenServiceTypeSchema),
  image_gen_model: v.nullable(v.string()),
  images_generated: NullableBigIntSchema,
  image_gen_processing_time: NullableBigIntSchema,
  image_gen_cost: v.nullable(v.pipe(v.number(), v.minValue(0))),
  selected_image_prompts: v.nullable(v.string()),
  image_files: v.nullable(v.string()),
  music_gen_enabled: NullableSqliteBooleanSchema,
  music_gen_service: v.nullable(MusicServiceTypeSchema),
  music_gen_model: v.nullable(v.string()),
  music_gen_genre: v.nullable(v.string()),
  music_gen_preset: v.nullable(MusicPresetSchema),
  music_gen_target_duration: NullableBigIntSchema,
  music_gen_instrumental: NullableSqliteBooleanSchema,
  music_gen_sample_rate: v.nullable(MusicSampleRateSchema),
  music_gen_bitrate: v.nullable(MusicBitrateSchema),
  music_gen_file: v.nullable(v.string()),
  music_gen_processing_time: NullableBigIntSchema,
  music_gen_duration: v.nullable(v.pipe(v.number(), v.minValue(0))),
  music_gen_cost: v.nullable(v.pipe(v.number(), v.minValue(0))),
  music_gen_lyrics_length: NullableBigIntSchema,
  music_gen_lyrics_generation_time: NullableBigIntSchema,
  music_gen_lyrics: v.nullable(v.string()),
  video_gen_enabled: NullableSqliteBooleanSchema,
  video_gen_service: v.nullable(v.string()),
  video_gen_model: v.nullable(v.string()),
  videos_generated: NullableBigIntSchema,
  video_gen_processing_time: NullableBigIntSchema,
  video_gen_cost: v.nullable(v.pipe(v.number(), v.minValue(0))),
  selected_video_prompts: v.nullable(v.string()),
  video_size: v.nullable(v.string()),
  video_duration: v.nullable(v.pipe(v.number(), v.minValue(0))),
  video_files: v.nullable(v.string()),
  document_backup_url: v.nullable(v.string()),
  document_backup_key: v.nullable(v.string()),
  document_backup_uploaded_at: NullableBigIntSchema,
  input_type: v.nullable(InputTypeSchema),
  audio_s3_url: v.nullable(v.string()),
  tts_s3_url: v.nullable(v.string()),
  image_s3_urls: v.nullable(v.string()),
  music_s3_url: v.nullable(v.string()),
  video_s3_urls: v.nullable(v.string()),
  thumbnail_s3_url: v.nullable(v.string())
})
